config/routes.rb
Rails.application.routes.draw do


  get 'landings/index'

  get 'company/show'

  resources :jobs do
    member do
      get 'apply'
    end
    resources :job_applications, as: :applications
  end

  resources :companies do
    resources :jobs do
      resources :job_applications, as: :applications, only: [] do
        member { get 'approve' }
      end
    end
  end

  devise_for :employees, controllers: {
    registrations: 'employees/registrations',
    sessions: 'employees/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'landings#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
  has_many :jobs
  has_many :users
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :jobs, dependent: :destroy
  has_many :employees, dependent: :destroy
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities, dependent: :destroy
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :company_employee
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :company, optional: true
  validate :company_exist, on: :create

  def company_exist
    company = Company.find_by(name: company_employee)
    if company.present?
      errors[:base] << 'La empresa ingresada ya existe'
    else
      company = Company.create(name: company_employee)
      self.company = company
    end
  end
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :city
  belongs_to :company
  has_many :job_applications, dependent: :destroy
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :user
  belongs_to :job
  validates_uniqueness_of(:user_id, scope: :job_id)

  before_save :default_status
  enum status: [:pending, :approved, :rejected]

  def default_status
    self.status ||= 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :job_applications
  belongs_to :city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def iframe_view
    response.headers.delete "X-Frame-Options"
  end

  def after_sign_in_path_for(resource)
    if resource.is_a?(Employee)
      job_path(current_employee.company_id)
    else
      super
    end
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
    @jobs = @company.jobs
  end
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  def show
    @company = Company.find(params[:id])
  end
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :authenticate_employee!, only: [:approve]

  def create
    @job = Job.find(params[:job_id])
    JobApplication.create(user: current_user, job: @job)
    redirect_to jobs_path, notice: 'Has postulado'
  end

  def approve
    @job = Job.find(params[:job_id])
    @job_application = JobApplication.find(params[:id])
    @job_application.approved!
    JobMailer.approved_notification(@job_application.user, @job_application.job).deliver_later
    redirect_to [@job.company, @job]
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :iframe_view, only: [:index, :show, :apply]
  before_action :authenticate_user!, only: :apply


  # GET /jobs
  # GET /jobs.json
  def index
    @q = params[:q]
    @jobs = Job.includes(:city, :company)
    @jobs = @jobs.where('name like ?', "%#{@q}%") if @q.present?

    @my_applications = user_signed_in? ? JobApplication.where(user: current_user) : []
  end

  def apply
    @job = Job.find(params[:id])
    render plain: "Postulando a #{@job.description}"
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:status, :description, :city_id)
    end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  layout false
  def index
    @jobs = Job.last(5)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/job_applications_helper.rb
module JobApplicationsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status, id: :job_status %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :job_description %>
  </div>

  <div class="field">
    <%= form.label :city_id %>
    <%= form.text_field :city_id, id: :job_city_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Trabajos </h1>

<table>
  <thead>
    <tr>
      <th>Name, Description</th>
      <th>Compañía</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td>
            <h5> <%= job.name %> </h5>
            <%= job.description %>
        </td>
        <td><%= job.company.try(:name) %></td>
        <td><img src="<%= job.company.try(:photo) %>" width="128" height="96"></td>

        <td><%= job.city.try(:name) %></td>
        <td>
          <% if @my_applications.any?{|a| a.job_id == job.id} %>
            Postulando
          <% else %>
            <%= link_to 'Postular', job_applications_path(job), method: :post %></td>
          <% end %>
        <!-- <td><%#= link_to 'Edit', edit_job_path(job) %></td>
        <td><%#= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.slim
.card.horizontal
  .card-image
    =image_tag(@job.company.photo)
  .card-stacked
    .card-content
      h4= @job.name
      p= @job.description

- if employee_signed_in?

  h3 Postulaciones

  table.striped
    tr
      th colspan=2 Datos
      th Perfil postulante
      th Estado
      th Opciones
    - @job.job_applications.each do |ja|
      tr
        td= ja.user.name
        td= ja.user.email
        td= link_to "Perfil", "#modal#{ja.user.id}", class:"waves-effect waves-light btn"
        td= ja.status
        - unless ja.approved?
          td= link_to "Aceptar", approve_company_job_application_path(@job.company, @job, ja)
        div id="modal#{ja.user.id}" class="modal bottom-sheet"
          div class="modal-content"
            h4= ja.user.name
            p= ja.user.profile
          div class="modal-footer"
            - unless ja.approved?
              = link_to "Aceptar Postulación", approve_company_job_application_path(@job.company, @job, ja), class:"modal-action modal-close waves-effect waves-green btn-flat"