config/routes.rb
Rails.application.routes.draw do


  get 'landings/index'

  get 'company/show'

  resources :jobs do
    member do
      get 'apply'
    end
    resources :job_applications, as: :applications
  end

  resources :companies do
    resources :jobs do
      resources :job_applications, as: :applications, only: [] do
        member { get 'approve' }
      end
    end
  end

  devise_for :employees, controllers: {
    registrations: 'employees/registrations',
    sessions: 'employees/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'landings#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
  has_many :jobs
  has_many :users
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :jobs, dependent: :destroy
  has_many :employees, dependent: :destroy
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities, dependent: :destroy
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :company_employee
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :company, optional: true
  validate :company_exist, on: :create

  def company_exist
    company = Company.find_by(name: company_employee)
    if company.present?
      errors[:base] << 'La empresa ingresada ya existe'
    else
      company = Company.create(name: company_employee)
      self.company = company
    end
  end
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :city
  belongs_to :company
  has_many :job_applications, dependent: :destroy
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :user
  belongs_to :job
  validates_uniqueness_of(:user_id, scope: :job_id)

  before_save :default_status
  enum status: [:pending, :approved, :rejected]

  def default_status
    self.status ||= 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :job_applications
  belongs_to :city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def iframe_view
    response.headers.delete "X-Frame-Options"
  end

  def after_sign_in_path_for(resource)
    if resource.is_a?(Employee)
      job_path(current_employee.company_id)
    else
      super
    end
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
    @jobs = @company.jobs
  end
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  def show
    @company = Company.find(params[:id])
  end
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :authenticate_employee!, only: [:approve]

  def create
    @job = Job.find(params[:job_id])
    JobApplication.create(user: current_user, job: @job)
    redirect_to jobs_path, notice: 'Has postulado'
  end

  def approve
    @job = Job.find(params[:job_id])
    @job_application = JobApplication.find(params[:id])
    @job_application.approved!
    JobMailer.approved_notification(@job_application.user, @job_application.job).deliver_later
    redirect_to [@job.company, @job]
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :iframe_view, only: [:index, :show, :apply]
  before_action :authenticate_user!, only: :apply


  # GET /jobs
  # GET /jobs.json
  def index
    @q = params[:q]
    @jobs = Job.includes(:city, :company)
    @jobs = @jobs.where('name like ?', "%#{@q}%") if @q.present?

    @my_applications = user_signed_in? ? JobApplication.where(user: current_user) : []
  end

  def apply
    @job = Job.find(params[:id])
    render plain: "Postulando a #{@job.description}"
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:status, :description, :city_id)
    end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  layout false
  def index
    @jobs = Job.last(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/job_applications_helper.rb
module JobApplicationsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myworld</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/js/materialize.min.js"></script>

  </head>

  <body>
    <nav>
      <div class="nav-wrapper indigo">
        <a href="#" class="brand-logo center">MyWorld</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="javascript:void(0)">Orientación</a></li>
          <li><a href="<%= new_employee_session_path %>">Eres empresa</a></li>
          <% if user_signed_in? %>
            <li> Hola <%= current_user.name %></li>
            <li><a href="<%= destroy_user_session_path %>" data-method="DELETE">Salida</a></li>
          <% elsif employee_signed_in? %>
            <li> Hola <%= current_employee.name %></li>
            <li><a href="<%= destroy_employee_session_path %>" data-method="DELETE">Salida</a></li>
          <% else %>
            <li><a href="<%= new_user_session_path %>">Ingreso</a></li>
            <li><a href="<%= new_user_registration_path %>">Registro</a></li>
          <% end %>
        </ul>
      </div>
      <div class="nav-wrapper indigo darken-1">
        <div class="row">
          <div class="col l4 offset-l4">
            <form action="<%= jobs_path %>" method="GET">
                   <div class="input-field">
                     <input id="search" type="search" name="q" required value="<%= @q%>">
                     <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                     <i class="material-icons">close</i>
                   </div>
                 </form>
            </div>
          </div>
      </div>
    </nav>

    <div> <%= notice %> </div>
    <div> <%= alert %> </div>

    <div class="container">
      <%= yield %>
    </div>

    <footer class="page-footer indigo lighten-2">
            <div class="container">
              <div class="row">
                <div class="col l6 s12">
                  <h5 class="white-text">Links de ayuda</h5>
                  <p class="grey-text text-lighten-4">
                    <ul>
                      <li><a class="grey-text text-lighten-3" href="#!">Emergencias</a></li>
                      <li><a class="grey-text text-lighten-3" href="#!">Salud</a></li>
                      <li><a class="grey-text text-lighten-3" href="#!">Orientación Legal</a></li>
                    </ul>
                  </p>
                </div>
                <div class="col l4 offset-l2 s12">
                  <h5 class="white-text">Links de ayuda</h5>
                  <ul>
                    <li><a class="grey-text text-lighten-3" href="#!">Orientación Educación</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Escuela de idiomas</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Mujeres en riesgo</a></li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="footer-copyright indigo">
              <div class="container">
              © 2017 Proyecto Para Ganar AngelHack
              </div>
            </div>
          </footer>

  </body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Myworld</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/js/materialize.min.js"></script>
</head>
<body>

</body>
</html>